### ISSUE TITLE
Upload database action failing

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/osv-offline#288]
The [Upload database][1] has been failing since https://github.com/renovatebot/osv-offline/commit/8e99a29d26be591eb703c71404e3d4788b72c1a9 on the the 1st April. The error is:

```
/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/util.js:62
    return value.replace(backslashRegExp, directorySeparator);
                 ^

TypeError: value.replace is not a function
    at normalizeSlashes (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/util.js:62:18)
    at Object.getExtendsConfigPath (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/ts-internals.js:24:54)
    at readConfig (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/configuration.js:127:64)
    at findAndReadConfig (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/configuration.js:50:84)
    at phase3 (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/bin.js:254:67)
    at bootstrap (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/runner/work/osv-offline/osv-offline/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
```

and is due to `ts-node`'s lack of support for TypeScript 5.0's extends array.

This was resolved in https://github.com/TypeStrong/ts-node/pull/1958 but is not yet available in a release. The two options are to:

1. Rollback to a single extends
2. Use `ts-node` from GitHub instead of npm

[1]: https://github.com/renovatebot/osv-offline/actions/workflows/update.yml
